### ISSUE TITLE
Developer version?

### ISSUE THREAD

**Issue by AndyButland** [enkelmedia/TheDashboard#1]
This looks great and reminded me of something we discussed on the retreat this year - basically a developer versions of this, showing you all your application handlers, custom routes, hijacked routes custom content finders, events etc.  Thinking was this might be quite useful when picking up work on a site, just to see all the things that are configured and maybe not so easy to hunt down in code.

I may (time depending... no promises at this stage!) give this some more thought... but if so firstly wondered if you think it would make sense as part of this package?  So you get "TheDashboard" (for editors) and "TheDevDashboard" (perhaps... for developers) appearing in the "Developer" section.

**Comment by enkelmedia** [comment]
Thank Andy! Why not!? Sounds like a great contribution if you are up for it =D I would say that we could include both of them in "The Dasboard"-package! Why not? =D

**Comment by AndyButland** [comment]
Great, glad you think it makes sense as part of this.  Will give it some thought.

**Comment by enkelmedia** [comment]
Will be included in the next release =D

**Comment by enkelmedia** [comment]
Included in latest release (v1.1): https://our.umbraco.org/projects/backoffice-extensions/the-dashboard/
