### ISSUE TITLE
The "entryPoint" extension-type is deprecated, please use the "backofficeEntryPoint"

### ISSUE THREAD

**Issue by a-t-k** [enkelmedia/TheDashboard#105]
Version 15.0.0

The "entryPoint" extension-type is deprecated, please use the "backofficeEntryPoint" in manifest.

**Comment by enkelmedia** [comment]
I’ll probably adress that in future versions. Does it cause you any issues in 15.0.0?

**Comment by enkelmedia** [comment]
Fixed here https://github.com/enkelmedia/TheDashboard/issues/105
