### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by kipusoep** [enkelmedia/TheDashboard#11]
It would be great if you could create a NuGet package of this package.

**Comment by enkelmedia** [comment]
True =D I think we have everything in place for that so it's just a matter of adding it to nuget =D I'll have a look when I find the time.

**Comment by kipusoep** [comment]
Why close the issue when it's not resolved yet? :-/

**Comment by enkelmedia** [comment]
@kipusoep haha =D To fast on the buttons =D

**Comment by kipusoep** [comment]
:+1:

**Comment by kipusoep** [comment]
Hi, any updates on this?

**Comment by enkelmedia** [comment]
Nope haven't have time - if someone would like to contribute - feel free

**Comment by kipusoep** [comment]
I'll have a look at it.

**Comment by KirschnerMatt** [comment]
Any update on this? A Nuget package would make this super easy.

**Comment by enkelmedia** [comment]
Hi! Still the same "status" I'm afraid. Would you like to contribute?

**Comment by enkelmedia** [comment]
Hi! 

Give this a go =D 

https://www.nuget.org/packages/Our.Umbraco.TheDashboard/
