### ISSUE TITLE
Gravatar should be loaded over HTTPS

### ISSUE THREAD

**Issue by KirschnerMatt** [enkelmedia/TheDashboard#15]
This should be a simple fix on line 24 of \Core\UserAvatarProvider.cs

I've fixed it for my own project and will attempt a pull request. I've never done one of these before so this will be a nice learning experience.

**Comment by KirschnerMatt** [comment]
Added a new pull request: https://github.com/enkelmedia/TheDashboard/pull/16

**Comment by enkelmedia** [comment]
Thanks for the PR!
