### ISSUE TITLE
Developer tab error - ReflectionTypeLoadException

### ISSUE THREAD

**Issue by KirschnerMatt** [enkelmedia/TheDashboard#17]
Installing this package on Umbraco 7.4.3 will cause rendering issues and an error on the backoffice Developer tab.

The error is thrown in TheDashboard.Data.UmbracoRepository.UmbracoRepository.cs on the method GetNonCoreTypesAssignableFrom.

The error:
A first chance exception of type 'System.Reflection.ReflectionTypeLoadException' occurred in mscorlib.dll

Additional information: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by enkelmedia** [comment]
Thanks! We'll have a look at this =D

**Comment by AndyButland** [comment]
I have seen something similar with Umbraco 7.4+ and another package I work on actually.  Same thing was [reported here](https://our.umbraco.org/projects/website-utilities/personalisation-groups/issues-and-feedback/76753-anyone-tried-on-74).  Have sent you a PR that I believe should resolve the issue.

**Comment by KirschnerMatt** [comment]
Andy's PR seems to have fixed the issue. Thanks, Andy!

https://github.com/enkelmedia/TheDashboard/pull/18

**Comment by AndyButland** [comment]
Great - thanks for reporting and then updating on the fix.
