### ISSUE TITLE
Layout update - numbers moved to top row

### ISSUE THREAD

**Issue by KirschnerMatt** [enkelmedia/TheDashboard#19]
I didn't particularly care to have my recent activity shoved below Unpublished Content, as that section is quite long and I was forced to scroll to see the previously mentioned section. I went ahead and updated the layout of TheDashboard.html to better display all sections without having to scroll. If you like this (image below), I could easily reproduce my changes in a pull request.

![image](https://cloud.githubusercontent.com/assets/9557207/14822265/f8348f82-0b9b-11e6-8531-969d004b3351.png)

* PS: also fixed a typo on Recent Activit**i**es

**Comment by enkelmedia** [comment]
Hi!

I think I like it! You're right about the fact that it's better to have them in separate columns. I would love a PR on this one =D

**Comment by KirschnerMatt** [comment]
No problem. Pull request here: https://github.com/enkelmedia/TheDashboard/pull/20
