### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by GaryHenshall** [enkelmedia/TheDashboard#22]
I have recently uninstalled this package although i think it was a very nice simple dashboard. After uninstalling it, i found that the Dashboard.config file was still looking for "The Dashboard" content "Welcome" dashboard. So i had to go in manually and remove this section. 

Not a big issue, just thought i would make you aware. 

Kind Regards.

**Comment by enkelmedia** [comment]
Thanks!

**Comment by enkelmedia** [comment]
Hi again!

Thanks for reporting this. It's ben solved and included in version 1.2.

// m
