### ISSUE TITLE
Add a loading spinner to the total nodes published counters

### ISSUE THREAD

**Issue by PeteDuncanson** [enkelmedia/TheDashboard#23]
When you first load up the dash board on a site with a lot of content (4000+ pages) it can take a while for the totals in the circles to be populated so the whole page looks a little blank.

Would be nice to give the user a little feedback that something is happening by putting a loading spinner/throbber in the circles themselves (or similar).

Additionally could the stats not be cached so they load up quicker initially and then refresh in the background? The stats might be out of date initially but it would give the perception of improved performance. Currently with everything blank users think the page is broken/empty so move off too quickly before it loads up losing some of the goodness of the dash board.

**Comment by PeteDuncanson** [comment]
Possibly a message under the cached results saying "refreshing please wait" with a throbber or something to highlight that the stats might be a little out of date. If they are refreshed and stored in the cache then they would be updated by any user hitting the page so shouldn't get too out of date thinking about it. Could even save the stats to disc for super fast start up but then you'd hit issue when load balanced.

**Comment by akeilox** [comment]
Second this. It would be great if sections support lazy loading with a spinner/message - as in current form the entire UI hangs till all of them are loaded.

**Comment by enkelmedia** [comment]
Great stuff! @PeteDuncanson @akeilox 
Are anyone of you keen for a PR? I might find time during the summer but not right now I'm afraid.

**Comment by PeteDuncanson** [comment]
I'll take a look. Didn't post to say it needed doing right now, just logging the idea down so we don't lose it :)

**Comment by enkelmedia** [comment]
@PeteDuncanson Great =D

**Comment by enkelmedia** [comment]
@PeteDuncanson Added an <umb-load-indicator> in V1.3. Thanks for reporting the issue! Cheers!
