### ISSUE TITLE
Feature Request - Opening Dashboard links in separate tabs

### ISSUE THREAD

**Issue by blachawk** [enkelmedia/TheDashboard#25]
I just installed this package into Umbraco 7.6.3. and it works great so far in my opinion.  What developer steps can I can to modify the package so that when I click on links in the dashboard, that they open up in separate tabs, not the same window?

Thanks

**Comment by enkelmedia** [comment]
Hi! 
I guess you could just add target="_blank" to the links?

**Comment by blachawk** [comment]
Ah yes, very easy to implement.  Thanks

**Comment by enkelmedia** [comment]
Please let me know if this works for you - might be something that we can add as a setting in the future.
