### ISSUE TITLE
Feature Request - Approval Requests

### ISSUE THREAD

**Issue by blachawk** [enkelmedia/TheDashboard#27]
This is not an issue, but I do not see a specific place on Our Umbraco to make this request.  Would there be any plans to include a section in TheDashboard that would list all content nodes that are "waiting for approval" Perhaps this is already possible to configure and setup within the package? 

I see the following in theDashboard.html file

```   
<p ng-show="item.logItemType =='Save'">
  <strong>{{item.userDisplayName}}</strong> <localize key="theDashboard_saved">saved</localize> <a target="_blank" href="/umbraco/#/content/content/edit/{{item.nodeId}}">{{item.nodeName}}</a> <localize key="theDashboard_butDidNotPublish">but did not publish</localize>.
</p>
```

Is there a simular thing we can do, to also add approval requests to this html file?

Thanks for any advice!

**Comment by enkelmedia** [comment]
Hi! 

Would probably be something that can be done - the source is here on github - if you would like to implement it I'm happy to work with you on a pull request for this. 

Cheers!
