### ISSUE TITLE
404 Not found when using custom CMS Prefix

### ISSUE THREAD

**Issue by mikhey** [enkelmedia/TheDashboard#28]
I encountered an issue when using a custom cms prefix for Umbraco.  I fixed it by updating the controller.js files.  See below for the changes:

**TheDashboard.controller.js, Line 5:**
From:
`$http.get('/umbraco/backoffice/api/TheDashboard/GetViewModel')`
To:
`$http.get('backoffice/api/TheDashboard/GetViewModel')`

**TheDevDashboard.controller.js, Line 5:**
From:
`$http.get('/umbraco/backoffice/api/TheDevDashboard/GetViewModel')`
To:
`$http.get('backoffice/api/TheDevDashboard/GetViewModel')`

**Comment by enkelmedia** [comment]
Cool! Would you like to create a pull request?

**Comment by mikhey** [comment]
Sure, haven't done that before tbh.  I should be able to get to it this week sometime.

**Comment by enkelmedia** [comment]
Solved in V1.3, thanks for reporting the issue!
