### ISSUE TITLE
TheDashboard not loading on Umbraco 7.6.7

### ISSUE THREAD

**Issue by blachawk** [enkelmedia/TheDashboard#31]
I have a fresh instance of Umbraco 7.6.7 installed.  I installed TheDashboard via Nuget 
`Install-Package Our.Umbraco.TheDashboard -Version 1.2.0`  

The installation reports as successful.  But when I go back into Umbraco BackOffice and visit the content section, there is no dashboard tab.  

Am I missing something?

**Comment by enkelmedia** [comment]
Hi!

Did you have your permissions correctly set up? The installer need to write to /config/dashboard.config

Any errors or so? Does the tab show up at all?

**Comment by tom-d8** [comment]
In recent versions of Umbraco the dashboard .config file is not updated on install. You can manually add this to the dashboard.config file to get TheDashboard to show

  <section alias="TheDashboard">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Welcome">
      <control addPanel="true" panelCaption="">/app_plugins/TheDashboard/TheDashboard.html</control>
    </tab>
  </section>

**Comment by enkelmedia** [comment]
@tom-d8 How do you mean with "recent versions of Umbraco"? Did something change in the core?

**Comment by tom-d8** [comment]
I assumed the exact structure of the dashboard.config file changed and that wasn't handled properly by this package, so it failed to write the necessary section. I think it happened around 6 months ago.

Of course I could be totally wrong here as I didn't investigate at the time (my bad!), but manually adding the necessary section fixed it. We start each new project from a vanilla install we have so we only had to so the manually once.

regards
t

**Comment by enkelmedia** [comment]
@tom-d8  Okey I see - I have not noticed if the structure has changed - I'll check. Are you sure that you had the permissions settings right during this install? 9 out of 10 times this is the issue, that the installer don't have the right permissions to the folder. 

Did you install using nuget or using the package installer in the backoffice?

**Comment by tom-d8** [comment]
Installed via Nuget.

I'm pretty sure the permissions are okay, they're standard settings we've been using for 10 years.

The Examine Management packages seems to install itself okay into the dashboard, but I'll double check both these packages in a clean install and let you know what happens

regards
t

**Comment by tom-d8** [comment]
in a fresh install of 7.8, I installed TheDashboard but it didn't update dashboard.config. I then installed Examine Management and it did update dashboard.config. Both were installed via nuget

HTH
t

**Comment by tom-d8** [comment]
p.s. I also installed the latest Nexu and it also updated dashboard.config
t

**Comment by enkelmedia** [comment]
@tom-d8 Thanks for trying again - I'll have a look to see if there is something missing around this.

**Comment by enkelmedia** [comment]
Hi! Turns out that there where no transformations for the nuget-package install. I've added this to v1.3. Hope this works now =D Thanks for reporting the issue!
