### ISSUE TITLE
Feature Request - exclude certain users from recent activities

### ISSUE THREAD

**Issue by tom-d8** [enkelmedia/TheDashboard#35]
We have a scheduled task to add and update nodes from an external source. This will swamp the Recent Activity list. Is there a way to exclude a specific user, even if it's just adding their Id to a config file?

TIA
t
p.s. great package, one of the first I install on new projects

**Comment by enkelmedia** [comment]
Hi!
There is no setting for this at the moment, I would clean out the log after your batch-job (and maybe the content history) to avoid the db to get bloated.
