### ISSUE TITLE
User 0 constantly Saving items

### ISSUE THREAD

**Issue by phunkb** [enkelmedia/TheDashboard#43]
Hi, I made a post on our.Umbraco but im not sure if the plugin is acting up;
https://our.umbraco.com/forum/using-umbraco-and-getting-started//94491-first-user-with-id-0-is-constantly-reported-as-saving-but-not-publishing-in-the-dashboard-plugin

Basically, user with ID 0 is reported as constantly saving items, but i know that nobody is doing it.

Any ideas? love the package, thank you.

**Comment by enkelmedia** [comment]
Hi!

Let's talk about this in the forum first and then create an issue here if we find out that something is wrong =D

https://our.umbraco.com/forum/using-umbraco-and-getting-started//94491-first-user-with-id-0-is-constantly-reported-as-saving-but-not-publishing-in-the-dashboard-plugin
