### ISSUE TITLE
Umbraco 8 support?

### ISSUE THREAD

**Issue by lcichanowicz** [enkelmedia/TheDashboard#47]
Greetings, @enkelmedia.  Are there plans for an Umbraco 8 version of TheDashboard?

**Comment by enkelmedia** [comment]
I started to look at it a while ago but at the time there was some bugs in the "LogItemService" in the core, since then I haven't looked at it - might be in the next weeks but I can't promies =D

**Comment by lcichanowicz** [comment]
Thanks for the rapid reply, @enkelmedia.  I am considering downgrading to Umbraco 7 anyway.  The general lack of packages is just too limiting.

**Comment by enkelmedia** [comment]
@lcichanowicz the V8-version is not released =D Feel free to post any issues here in the issue-tracker. 

All the best!
