### ISSUE TITLE
Activity missing - v8 variants

### ISSUE THREAD

**Issue by stefankip** [enkelmedia/TheDashboard#48]
Ola! Nice package!
I think there's some kind of issue with the activity feed; I am sure a lot of content has been created by an umbraco cloud user, but I don't see any of that on the dashboard.
Is this a known issue? Might be related to umbraco cloud, but I'm not sure.

**Comment by enkelmedia** [comment]
Hi!

Thanks for reaching out!

We’re using the umbracoLog-table to fetch activity, are you sure that this data is there? Can you see the activity log on the actual content-node but not in the dashboard?

**Comment by stefankip** [comment]
No problem, thank you for building this dashboard!

I ran the SQL query and there are many entries which are not shown.
Though I am unable to locate the piece of code responsible for this.
Could it be that this is caused by variants?

**Comment by enkelmedia** [comment]
Hi!

We do some filtering after the query comes back, the most prominent one being that we only show the latest activity for each node, so if one save, publish, unpublish and then publish we will not show this as 4 activities, we'd only show the last publish for this node. So one node will only show once. Not sure if this is what you are seeing?

Might also be something around variants... but if you get data back from the SQL-statement it sounds strange.

**Comment by stefankip** [comment]
I sent you a tweet with a screenshot :-)

**Comment by enkelmedia** [comment]
Thanks @stefankip !

Its definitely a lack of support for certain "logHeaders" related to Language Variants that is the problem here.

We need to support these types of headers as well:

* SaveVariant
* PublishVariant

Maybe more? It would also be nice to indicate the language in the activity dashboard, so when saving/publishing the "Swedish" variant this is indicated in some way. Not sure if the "language names" are translated as well but need to look at that.

**Comment by ronaldbarendse** [comment]
I also don't see any activity on save/publish of culture variant pages (only a rollback). This doesn't seem to be related to Umbraco Cloud, as it also doesn't work locally; the issue title should be updated to reflect the problem that's now correctly identified.

Besides `SaveVariant`and `PublishVariant`, there's also `UnpublishVariant`: all have one or more (comma seperated) language name in the `parameters` column. This can be used in the dasboard text; the languages themselfs aren't translated (and might become editable: https://github.com/umbraco/Umbraco-CMS/pull/8384).

**Comment by enkelmedia** [comment]
Thanks for the update, I'll try to find some time to work on this the upcoming week, if it's urgent feel free to create a PR and I'll make sure to merge it.
