### ISSUE TITLE
Idea: The Content App

### ISSUE THREAD

**Issue by TimGeyssens** [enkelmedia/TheDashboard#49]
Pretty much the dashboard but on a content app, and just list activity for the stuff happening on the content node where it is placed and bellow... would make sense in multi site instances... :)

**Comment by enkelmedia** [comment]
While I like the idea I've decided to keep the package extremely simple. I'll keep this here as an issue but at the moment I will not work actively on it - someone (I guess me) also has to maintain, upgrade, bugfix and so on so with that in mind I want to keep the code base small and clean.

**Comment by TimGeyssens** [comment]
Sure no worries, would you mind if I fork and work on that feature?

**Comment by enkelmedia** [comment]
Not at all! Om not saying no to include it, just that I cant work on it right now. I would love if you where to help. Also if we could collaborate on How we solve tvings and try to re-use as much as possible of what is already there. If you start working on it maybe we could have a chat Before to figure out how to do it?

**Comment by ronaldbarendse** [comment]
@TimGeyssens A content app only makes sense it it's only added to the root nodes of the different sites and shows all activity below that node (including itself).

The dashboard only shows activity for nodes you have access to (filtered by `UserToNodeAccessHelper`), so it would make more sense to filter/group the activity per site (e.g. using a dropdown). The sites/nodes should probably be manually added/specified though, as this might differ per setup.

**Comment by TimGeyssens** [comment]
@ronaldbarendse also nice idea :)

**Comment by TimGeyssens** [comment]
Indeed filtering might be a good option here... instead of content app overload

**Comment by enkelmedia** [comment]
I guess that it would be quite easy to filter based on the start of the tree path for the node.

On the other hand, like @ronaldbarendse says, a user will one see what he/she has access to see so in a multi site setup i guess that all changes To nodes that I can access is relevant.

Might close this and create a new issue/feature idea for the filter.

Cheers guys!

**Comment by enkelmedia** [comment]
Moved the stuff over here: https://github.com/enkelmedia/TheDashboard/issues/53
