### ISSUE TITLE
Problem with Umbraco 9 RC2

### ISSUE THREAD

**Issue by smarshallsay** [enkelmedia/TheDashboard#59]
TheDashboard seems to be causing issues with Smidge and not loading correctly, this is causing other dashboards to fail (Kevin Jump was kind enough to help me investigate as I initially thought it was a uSync issue)

Errors and discussion here https://our.umbraco.com/forum/umbraco-9//106992-umbraco-9-usync-dashboard-not-loading-after-publish-to-server#comment-333180

**Comment by enkelmedia** [comment]
Thanks for sharing!

Seems strange, does the file exist in that folder? 

From the error:
```
 System.IO.FileNotFoundException: No such file exists /app_plugins/Our.Umbraco.TheDashboard/TheDashboard.controller.js (mapped from /app_plugins/Our.Umbraco.TheDashboard/TheDashboard.controller.js)
File name: '/app_plugins/Our.Umbraco.TheDashboard/TheDashboard.controller.js'
```

I'm thinking that there might be some issue with coping the files, also if you are on RC2 we haven't release a version that supports RC2 the current release is tested on RC1. 

There is a PR that is waiting for review https://github.com/enkelmedia/TheDashboard/pull/58

**Comment by smarshallsay** [comment]
Thanks for your work :)

Yes the files do exist in the app_plugins folder, I've tried uninstallng and re-installing but it does not seem to help. It did seem to work fine in RC1

**Comment by enkelmedia** [comment]
Thanks for this I've just released a version for RC3 and will skip RC2.

https://www.nuget.org/packages/Our.Umbraco.TheDashboard/9.0.0-rc003
