### ISSUE TITLE
Users with multiple groups don't see anything

### ISSUE THREAD

**Issue by colin-tactuum** [enkelmedia/TheDashboard#63]
In Umbraco 8, I have users with multiple groups.
The first group has a start node of 'Content root' (-1) and the subsequent group start nodes are children of 'Content root'.  In my case 1070.
The line of code that sets _userStartNodes in UserToNodeAccessService.cs returns 2 nodes, but both are -1.
This results in the HasAccessTo method always returning false and the user never seeing any activity on the dashboard.

**Comment by enkelmedia** [comment]
Hi!

I can confirm that having "Content Root" and another node as "Content start nodes" for a User results in no content in the dashboard.

Can I ask why you would want to combine "Content Root" and a specific node? In the scenario "Content Root" would basically do nothing as far as I can see (tested on Umbraco 8.0.0 so might have changed).

Anyway it seems that if a given node is not visible in the tree the User will not have access to it. I'll try to see if i can fix this.

**Comment by enkelmedia** [comment]
Solved in V8-branch, need to check V9 as well so I'll keep the issue open.

**Comment by enkelmedia** [comment]
Not sure that this really fixes the issue. Can you describe exactly how your setup looks? And what version of Umbraco 8?

**Comment by colin-tactuum** [comment]
I will have time later today or tomorrow to look at this and I will get back to you.

My setup does only have one language.
