### ISSUE TITLE
Not showing in RC3

### ISSUE THREAD

**Issue by smarshallsay** [enkelmedia/TheDashboard#64]
Hi, I tried to install the latest version 9.0.0-rc003 on Umbraco 9 RC3 but it is not showing correctly in backoffice (just get a blank 'welcome' tab).
Note I did have an older version installed and working on RC2, but removed it when it wasn't working for RC3 so I wonder if there is any leftover data somewhere? (I deleted the plugin folder and DLLs after uninstalling)
The error in the chrome console is:

umbraco-backoffice-js.js.v1:152 
Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.0/$controller/ctrlreg?p0=Our.Umbraco.TheDashboard.Controller
    at umbraco-backoffice-js.js.v1:32
    at umbraco-backoffice-js.js.v1:123
    at ea (umbraco-backoffice-js.js.v1:105)
    at p (umbraco-backoffice-js.js.v1:96)
    at g (umbraco-backoffice-js.js.v1:90)
    at umbraco-backoffice-js.js.v1:89
    at Object.link (umbraco-backoffice-js.js.v1:326)
    at umbraco-backoffice-js.js.v1:42
    at Ca (umbraco-backoffice-js.js.v1:114)
    at p (umbraco-backoffice-js.js.v1:98) '<div ng-include="property.view">'
(anonymous) @ umbraco-backoffice-js.js.v1:152

Any ideas?

Thank you!

**Comment by enkelmedia** [comment]
Looks like the js-file does not get included in the bundle, do you see the js-file on disk? Could it be cache-related? If there is a way to run without caching maybe?

**Comment by smarshallsay** [comment]
the TheDashboard.controller.js is in the app_plugins\our.umbraco.thedashboard folder, chrome cache is turned off. I also tried deleting the smidge folder and restarting, which as I understand it is v9's equivalent to clientdependency

**Comment by smarshallsay** [comment]
Aha I have found the issue, it seems the paths in the package.manifest are case sensitive. My App_Plugins folder is cased like this, I updated the paths in the manifest and it now works

`{
    "javascript" : [
        "/App_Plugins/Our.Umbraco.TheDashboard/TheDashboard.controller.js"
    ],
  "css": [
        "/App_Plugins/Our.Umbraco.TheDashboard/TheDashboard.css"
    ]
}`

**Comment by enkelmedia** [comment]
Hmm… are you running on Windows?

**Comment by smarshallsay** [comment]
Yep Windows 10

**Comment by smarshallsay** [comment]
This is affecting a Windows Server machine I just dpployed to also so I don't think its an issue related to my machine

**Comment by enkelmedia** [comment]
Thanks! I'll try and see if I can replicate and solve this.

**Comment by olibos** [comment]
Hello,

I had the same issue, I've added a PR to fix it 😉

Have a nice day,
Olivier

**Comment by enkelmedia** [comment]
Great stuff! I’ll have a look asap

**Comment by enkelmedia** [comment]
Should be fixed by the nice updates from @olibos

**Comment by olibos** [comment]
Thanks @enkelmedia , let me know when the new RC is available.
