### ISSUE TITLE
Localization: The Dashboard title/name is not translated

### ISSUE THREAD

**Issue by erikjanwestendorp** [enkelmedia/TheDashboard#75]
The name of the dashboard is not translated

![image](https://user-images.githubusercontent.com/7831614/153240768-92b0c00c-93b6-4b27-a5a7-1318299ae2f2.png)

**Comment by enkelmedia** [comment]
Thanks for reporting!

I’ll see when I can find time to fix that. Feel free to create a PR if this is urgent.

Cheers!

**Comment by erikjanwestendorp** [comment]
Thanks for your reply @enkelmedia I just made a PR
