### ISSUE TITLE
Retina image of avatars

### ISSUE THREAD

**Issue by bjarnef** [enkelmedia/TheDashboard#8]
You can use retina image for the avatars by using ```srcset``` attribute.
Then the avatars will be sharper on retina screens on tablets and phones.

Actually the natural size requested from Gravatar is 80x80px but css scale it to 55x55px .. so it would be better to request a size on 55x55px and then maybe just use ```border-radius: 50%``` for div.logitem img

2x and 3x describe the image for screens with DPR (device-pixel-ratio) on 2 and 3. So these images is just 2 and 3 times the original size. If srcset is not supported it fallback to src attribute, but it is pretty well supported by modern devices both tables and phones.

See this screenshot from my tablet in full size.
![screenshot_2015-08-15-15-04-42](https://cloud.githubusercontent.com/assets/2919859/9288945/ab6cc570-435f-11e5-9254-1187d6fd23a4.png)

```
<img src="http://www.gravatar.com/avatar/8ed42a9b60e5c5e8d3e829c724956698&amp;s=55" srcset="http://www.gravatar.com/avatar/8ed42a9b60e5c5e8d3e829c724956698&amp;s=110 2x, http://www.gravatar.com/avatar/8ed42a9b60e5c5e8d3e829c724956698&amp;s=165 3x">
```

**Comment by enkelmedia** [comment]
Sounds like a good idea!
