### ISSUE TITLE
Error after upgrading to 10.0.0 (from 9.0.0)

### ISSUE THREAD

**Issue by smarshallsay** [enkelmedia/TheDashboard#81]
Dashboard does not show and the following error is in the chrome JS console:
I uninstalled, deleted the thedashboard folder and reinstalled but the issue persists, rolling back to 9.0.1 does also not fix the issue?

`angular.js:15697 Possibly unhandled rejection: {"data":{"ExceptionMessage":"This instance has already started one or more requests. Properties can only be modified before sending the first request.","ExceptionType":"System.InvalidOperationException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","StackTrace":"   at System.Net.Http.HttpClient.CheckDisposedOrStarted()\r\n   at System.Net.Http.HttpClient.set_Timeout(TimeSpan value)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.<>c__DisplayClass1_0.<GetUserAvatarUrls>b__0()\r\n   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()\r\n   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.GetUserAvatarUrls(Int32 userId, String userEmail, String userAvatar, IAppCache cache)\r\n   at Our.Umbraco.TheDashboard.Mapping.LogEntryToRecentActivityMapper.Map(LogEntryDto dto)\r\n--- End of stack trace from previous location ---\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.CreateFrontendModelsFrom(List`1 dtos)\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.GetPending()\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.GetUserAvatarUrls(Int32 userId, String userEmail, String userAvatar, IAppCache cache)\r\n   at Our.Umbraco.TheDashboard.Mapping.LogEntryToRecentActivityMapper.Map(LogEntryDto dto)\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.CreateFrontendModelsFrom(List`1 dtos)\r\n   at lambda_method447(Closure , Object , Object[] )\r\n   at lambda_method445(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"backoffice/api/TheDashboard/GetPending","headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-UMB-XSRF-TOKEN":"CfDJ8Od2A7a1qitJoCuho1tfezNlMcTdTj49Id1PuvkmWpWY3wa8esK6RHhaPs_Y15pn3EoE7R5E8bQ-IMQQc-X38-t2pIgjr9TbBtj493zx4Ze4KaIh49yBTOIDx0fLmfehhuI2jP1bc5nmf3yTK3a-ybkGwRYeI_KaQvnzeYtY4Av3FtOBpqVp6jXXZCfYP4amuQ"}},"statusText":"","xhrStatus":"complete"}
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
g @ angular.js:18107
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
k @ angular.js:13473
v @ angular.js:13730
y.onload @ angular.js:13635
load (async)
(anonymous) @ angular.js:13618
s @ angular.js:13418
(anonymous) @ angular.js:13159
(anonymous) @ angular.js:18075
$digest @ angular.js:19242
$apply @ angular.js:19630
safeApply @ umbraco.services.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:1
(anonymous) @ umbraco.services.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
js @ LazyLoad.min.js:1
loadJs @ umbraco.services.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:1
(anonymous) @ umbraco.controllers.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:1
MainController @ umbraco.controllers.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:1
invoke @ angular.js:5208
S.instance @ angular.js:11814
p @ angular.js:10627
g @ angular.js:9942
g @ angular.js:9945
g @ angular.js:9945
(anonymous) @ angular.js:9807
(anonymous) @ angular.js:1968
$eval @ angular.js:19523
$apply @ angular.js:19622
(anonymous) @ angular.js:1966
invoke @ angular.js:5208
c @ angular.js:1964
Wc @ angular.js:1984
(anonymous) @ Application?umb__rnd=669529a6e0798978d300895ee1d5b7de2115dabe:143
e @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
t @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
setTimeout (async)
(anonymous) @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
c @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
add @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
(anonymous) @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
Deferred @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
then @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
S.fn.ready @ jquery.min.js?d=70866aabf8678d148f38ac1da4871ed63b451739:2
(anonymous) @ Application?umb__rnd=669529a6e0798978d300895ee1d5b7de2115dabe:141
i @ LazyLoad.min.js:1
p @ LazyLoad.min.js:1
load (async)
k @ LazyLoad.min.js:1
js @ LazyLoad.min.js:1
(anonymous) @ Application?umb__rnd=669529a6e0798978d300895ee1d5b7de2115dabe:1
angular.js:15697 Possibly unhandled rejection: {"data":{"ExceptionMessage":"This instance has already started one or more requests. Properties can only be modified before sending the first request.","ExceptionType":"System.InvalidOperationException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","StackTrace":"   at System.Net.Http.HttpClient.CheckDisposedOrStarted()\r\n   at System.Net.Http.HttpClient.set_Timeout(TimeSpan value)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.<>c__DisplayClass1_0.<GetUserAvatarUrls>b__0()\r\n   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()\r\n   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.GetUserAvatarUrls(Int32 userId, String userEmail, String userAvatar, IAppCache cache)\r\n   at Our.Umbraco.TheDashboard.Mapping.LogEntryToRecentActivityMapper.Map(LogEntryDto dto)\r\n--- End of stack trace from previous location ---\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.CreateFrontendModelsFrom(List`1 dtos)\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.GetPending()\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)\r\n   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory)\r\n   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)\r\n   at Our.Umbraco.TheDashboard.Extensions.UserExtensions.GetUserAvatarUrls(Int32 userId, String userEmail, String userAvatar, IAppCache cache)\r\n   at Our.Umbraco.TheDashboard.Mapping.LogEntryToRecentActivityMapper.Map(LogEntryDto dto)\r\n   at Our.Umbraco.TheDashboard.Controllers.TheDashboardController.CreateFrontendModelsFrom(List`1 dtos)\r\n   at lambda_method447(Closure , Object , Object[] )\r\n   at lambda_method445(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"backoffice/api/TheDashboard/GetAllRecentActivities","headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-UMB-XSRF-TOKEN":"CfDJ8Od2A7a1qitJoCuho1tfezNlMcTdTj49Id1PuvkmWpWY3wa8esK6RHhaPs_Y15pn3EoE7R5E8bQ-IMQQc-X38-t2pIgjr9TbBtj493zx4Ze4KaIh49yBTOIDx0fLmfehhuI2jP1bc5nmf3yTK3a-ybkGwRYeI_KaQvnzeYtY4Av3FtOBpqVp6jXXZCfYP4amuQ"}},"statusText":"","xhrStatus":"complete"}`

**Comment by enkelmedia** [comment]
Hi sorry for the late update on this.

What exact Umbraco version are you on and what database are you using?

// m

**Comment by enkelmedia** [comment]
There was an issue with the HttpClient that was used to check for gravatar-images. I've made some adjustments in v10.0.1 which should solve this.

Try to upgrade and see if this solves the issue. 

https://www.nuget.org/packages/Our.Umbraco.TheDashboard/
