### ISSUE TITLE
The Dashboard does not show

### ISSUE THREAD

**Issue by smarshallsay** [enkelmedia/TheDashboard#85]
Hi @enkelmedia,
I have an old website that I have migrated to Umbraco 11. It is fresh code but migrating the old database to Umbraco 10 and then Umbraco 11, because they removed migrations for older database versions from Umbraco 11...
After which I installed your package again at the latest version 11.0.0 and I get the following error in the JS console:

<img width="959" alt="chrome_elSXQtivtE" src="https://user-images.githubusercontent.com/5755133/215793958-c310a807-e101-4565-9304-3b60d59bbb5c.png">

I have tried rebuilding, cleaning, deleting smidge folder and checking the case of App_Plugins etc but all seems fine. Any ideas?!

**Comment by enkelmedia** [comment]
Hi!

What happens if you use the in memory settings and restart?

https://docs.umbraco.com/umbraco-cms/reference/configuration/runtimeminificationsettings

```
"Umbraco": {
  "CMS": {
    "RuntimeMinification": {
      "UseInMemoryCache": false,
      "CacheBuster": "Version"
    }
  }
}
```

**Comment by enkelmedia** [comment]
Great news! :) Then this must have been some kind of caching issue.
