### ISSUE TITLE
Layout issue on mobile devices

### ISSUE THREAD

**Issue by BarryFogarty** [enkelmedia/TheDashboard#87]
Hi,

Thanks for a great package.  When viewed on mobile devices the columns overlap (see screenshot).  It would be much better if they stacked instead.

![image-2023-04-28-09-34-23-303](https://user-images.githubusercontent.com/2164279/235921306-d6be7a86-a793-457d-a5d4-c0910f4dc2ad.png)

**Comment by BarryFogarty** [comment]
No worries - I'm not a frontend dev either 🙂

**Comment by enkelmedia** [comment]
Fixed by PR: https://github.com/enkelmedia/TheDashboard/pull/88
