### ISSUE TITLE
Dashboard not shown

### ISSUE THREAD

**Issue by photogsy** [enkelmedia/TheDashboard#89]
I've installed this package on Umbraco 10.4.1 but the dashboard isn't showing.
I noticed that the dll isn't in the bin directory and if I copy it from the package directory, Umbraco fails to start.
Any idea what could be going on here?

**Comment by amitch17** [comment]
Same symptoms here. Umbraco 11.3.1. (Dashboard 11.0) Works locally but not when built for deployment

Angular error in console:

![image](https://github.com/enkelmedia/TheDashboard/assets/18399155/05d9c6ad-eede-4e9c-bc27-e03ba73db46b)

**Comment by enkelmedia** [comment]
Hi guys!

This has to be related to something about how the published artifacts are packed in your scenarios. 

Do you have the same files in the App_Plugins folder on in the deployed version as you do locally?

The error message that you see @amitch17 indicates that the javascript controller is missing.

**Comment by enkelmedia** [comment]
Maybe something in this thread could help you out? https://github.com/enkelmedia/TheDashboard/issues/83

I'm also working on a Razor Class Library-version of the package that will probably make the deployment experience better.

**Comment by photogsy** [comment]
Hi sorry for radio silence, I will try the new version but to let you know, I was not seeing the dashboard even when running in debug in VS, so don't think it was a deployment issue for me.
Will try new version next week.

**Comment by photogsy** [comment]
Hi @enkelmedia, tried new version and same problem, still not showing anything at all.
I'm running in VS debugger if that makes a difference.

**Comment by enkelmedia** [comment]
Super-strange, already running this in multiple projects both in dev, stage and production.

Do you still see any folder called “Our.Umbraco.TheDashboard” in the “App_Plugins”-folder? If you do, remove this folder. Make sure to build the project, maybe also restart Visual Studio?

If this still does not work, could you explain more about your setup?

Also, if you could provide a step by step guide on how to re-produce? Starting from “dot net new Umbraco” (include tooling etc).

**Comment by photogsy** [comment]
@enkelmedia Argh my apologies, I hadn't realised that the NuGet install doesn't automatically figure out which version to install based on the Umbraco version, so I had installed the latest version on a v10 Umbraco. I have downgraded to 10.0.1 and it now shows up as expected.

Unfortunately the dashboard is not quite showing what I'd hoped; I was hoping to get a list of nodes where a _writer_ user had clicked "Send for approval", however it's just showing all nodes that have been saved but not published - _nearly_ the same, but not quite! Do you think I can make some relatively easy tweaks to the code to get what we need?

**Comment by amitch17** [comment]
@enkelmedia One more belated followup to say I did get this working.  My issue was with the CI pipeline (Azure devops) which hadn't removed the files from the older version in the destination slot. Once they were cleared out, all is good.

Thank you for a useful package and your attentive support!

**Comment by enkelmedia** [comment]
@photogsy The type of content that we list out of the box "is what is it" but if you have any specific needs you're more than welcome to fork the repository or create your own website specific version of The Dashboard.
