### ISSUE TITLE
nothing shows up

### ISSUE THREAD

**Issue by avatart0ph** [enkelmedia/TheDashboard#9]
hello,

this project looks promising. but, it has caused my site to slow down significantly.
also the only thing working is in the developer section.
The content section has empty circles in it unlike your sample.

Could the slowdown be caused by errors? i found errors in the log and fixing right now then i will try reinstalling and see.
Also, any chance we can see a user dashboard? 
Where it says when the user has last logged in?

**Comment by enkelmedia** [comment]
Hi! 
If you debug the requests to the server (using Google Developer tools ie.) is it any request that take a lot of time or that throws errors? Does the content tree still work? Is it a fresh install or a web site that has "been around"? Lots of content?

Is the errors in the log related to The Dashboard or to other thing in the site? External errors should not slow down the site.

A use dashboard might be a good idea! Why not? Feel free to work with it and create a PR that I'll have a look at.

Cheers!

**Comment by avatart0ph** [comment]
hello,
It was an error in the back office that got it to work.
nothing to do with the tool.
Also, performance was perfect when i got rid of ublogsy spam comments and the members created in ublogsy. had to delete them in the database. 

I have to extend your project to do the user dashboard because DEWD is no longer in umbraco 7. i previously used DEWD to pull user activities

thank you so much!:D

**Comment by avatart0ph** [comment]
i finished the entire thing and even had it working! unfortunately, the table i was querying was no longer used for a long time (http://issues.umbraco.org/issue/U4-4231). I did not know this because my version of umbraco 6 was still logging information in the database. I was wondering why the current session had no entries. >_<     ....  atleast i got to experience how to modify plugins for umbraco 7 now. this is my silver lining
