### ISSUE TITLE
Help understanding how to make custom dashboard content

### ISSUE THREAD

**Issue by Eaglef90** [enkelmedia/TheDashboard#99]
Hello,
 I am looking to add a custom content like the "Recent Activites" but don't know if that is possible. The hope is to add another box titled "Analitics Tracking", have it run some JS to see if the user is included or not in the analitics tracking and give them a clickable link to toggle the include flag. I have all the code for the JS and what not just not sure how to add another box to the dashboard and have it run/display my code. Is this possilbe to do and if so any help on getting it setup would be aprecaited.

**Comment by enkelmedia** [comment]
Hi!

The current version only allow adding custom counters using the IDashboardCounter. There are no extension point to add a custom box.

However, you could probably copy the html,css and javascript files and create your own custom version of the dashboard that uses the backend endpoints from the package. Or you could fork/copy the whole package and use it as a starting point for your own dashboard - that would of course require you to manually update the code if you want to upgrade the package in the future so probably not the most sustainable approach.

**Comment by Eaglef90** [comment]
Thanks for the quick response, unfortunatlly I don't have enough skill in programing or Umbraco to do a custom run like that. I do love your dashboard though, very nice to get quick info on what's going on.

**Comment by enkelmedia** [comment]
Happy you like the package :) I’ll go ahead and close the issue. Cheers!
